language: go
go:
  - '1.10'
script:
  - make lint
  - make test
  - make release -j3
deploy:
  provider: releases
  api_key:
    secure: vpEqIhJSHa0MPkuYfJDxZ6hsaROJ4Nfy4nOSXEUDJz9lgxaoVTw9v/gJd+PTd8IOMrr24Lxex52bM8gP6V/gAlgxw2RA+q5phCCwFB21dZcTKVAJLzFCuecr9moMKcYJNOB9K/Z9414U34tdjb2nMDfxc32WQzbxGMlTHIS56oqsSt9RpxgGnYLY0c/ngRYyYGAp7HXMN8c3mS7GupK39iwVMU9yDVMGBfoKSWq1/uPk3VvQAj1SUhCxI7fy0cFZjTO6fagMmMBPi5dQDAxEwjw4KJyJu87QabcZ8gJ2qmOyXDsSmqqK97KkLfDJxPI90IEB46UZbCYbyOttOe2WD9GQLjcerFMDHbFqPb8GJj5V2y2soty61BSHVvT36MOInVCYsLyxVIRuQbpVmXz8x2lJRtGNbkDRKffG6bq+D/Dp6Pucjv+ljW3e5C1p/BlnrgKY4/2fPj1+4kn9qr3OcNFMVVuDadp4IT1TqRalkRlcNltYHv8Tve6O407VEWpxIz+ZsiAJFSDFcWufbhapcTDy6fD5iNkcuyMa0WZrpkBGYfNr4cpEt5pFV0Ze5WFVa8aFqst0BPrxVwJrqZ1HduuD907+aW5qCM+bFfMhx2LbnwAqAOhq7EjA07dytfBh8ekDTYAwmyJ7MpWkto1MCx/zLZcxBYXsA99yFt16Ies=
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
